
Vagrant.configure("2") do |config|
  # Definisci la prima macchina virtuale (nodo 1)
  config.vm.define "node1" do |node|
    node.vm.box = "ubuntu/jammy64" # Utilizziamo Ubuntu 22.04 LTS (Jammy Jellyfish)
    node.vm.hostname = "node1"     # Nome hostname per la VM
    node.vm.network "private_network", ip: "192.168.56.101" # IP statico sulla rete privata
    node.vm.provider "virtualbox" do |vb|
      vb.memory = "1024" # 1GB di RAM
      vb.cpus = "1"      # 1 Core CPU
    end
    # Qui specifichiamo il file di provisioning da avviare per la configurazione.
    # Verrà eseguito lo script 'install_pg.sh' all'interno della VM.
    node.vm.provision "shell", path: "provision/node_1.sh" 
  end

  # Definisci la seconda macchina virtuale (nodo 2)
  config.vm.define "node2" do |node|
    node.vm.box = "ubuntu/jammy64" # Utilizziamo Ubuntu 22.04 LTS
    node.vm.hostname = "node2"     # Nome hostname per la VM
    node.vm.network "private_network", ip: "192.168.56.102" # IP statico sulla rete privata
    node.vm.provider "virtualbox" do |vb|
      vb.memory = "1024" # 1GB di RAM
      vb.cpus = "1"      # 1 Core CPU
    end
    # Qui specifichiamo il file di provisioning da avviare per la configurazione.
    # Verrà eseguito lo script 'install_pg.sh' all'interno della VM.
    node.vm.provision "shell", path: "provision/node_2.sh" 
  end
end